### ISSUE TITLE
Bionic can't seem to load without an Internet connection

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#330] opened 2024-01-14 21:56 UTC
### Describe your issue

I tried to load Bionic without an Internet connection.

The reason for this is that I want to be able to do a fully air gapped standalone demo of running Bionic as it's own system.

It appears that there are some things in the code that require DNS lookups and when there is no DNS the lookups fail.

Is this fixable? I must be able to start and run Bionic in a full disconnected/off network use case.

### Describe your setup/startup scripts

normal startup.

### Steps to reproduce

try starting Bionic without an internet connection.

### What was the expected result?

I expect Bionic to be able to start and run on a private closed network without any internet, dhcp or routing. Just localhost

**Comment by ianpurton** [comment] 2024-01-15 04:29
Can you say what didn't start? Which service?

**Comment by tbendien** [comment] 2024-01-15 04:43
A bunch of things, dns lookups and access to the web UI. I didn't save any logs, suggest just trying to start once of your machines disconnected from Internet and see what happens. I'll see if I can get some logs for you tomorrow.

**Comment by ianpurton** [comment] 2024-01-15 13:33
Duplicate of https://github.com/bionic-gpt/bionic-gpt/issues/256

**Closed by ianpurton** 2024-01-15 13:33 UTC
