### ISSUE TITLE
Got data ingested issue for json file

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#357] opened 2024-02-06 15:16 UTC
### Describe your issue

It keeps dataset processsing status as "Queued" while testing with JSON file

### Describe your setup/startup scripts

docker-compose -f docker-compose.yml -f docker-compose-gpu.yml up

### Steps to reproduce

1. Access to the BionicGPT UI.
2. Create new data set and upload JSON file.
https://drive.google.com/drive/folders/1hHxQ5bkk8ozjxzd03JYUpI0YSLzdUIlt?usp=sharing
3. The JSON file ingestion status was keeping as "Queued" forever.

### What was the expected result?

The app can ingest the data and processed the Json file.

### Any additional information

Testing JSON file
https://drive.google.com/drive/folders/1hHxQ5bkk8ozjxzd03JYUpI0YSLzdUIlt?usp=sharing

**Comment by 9876691** [comment] 2024-02-10 13:11
To reproduce this issue

```
docker run -it -p 8000:8000 downloads.unstructured.io/unstructured-io/unstructured-api:4ffd8bc
```

```
curl -X 'POST' \
'http://localhost:8000/general/v0/general' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'files=@CONTRIBUTING.md' \
| jq -C .
```

Looks like unbstructured returns an empty array for this.

**Comment by 9876691** [comment] 2024-02-10 13:33
Issue raised with unstructured https://github.com/Unstructured-IO/unstructured-api/issues/366

**Comment by felixepiklah** [comment] 2024-02-15 03:20
Hi @9876691,

Thank you for your reply, 
I will also follow up the ticket.

Thanks & Regards,
Felix Nguyen

**Comment by 9876691** [comment] 2024-02-23 12:51
I'll close this as it's an unstructured issue not an issue with Bionic.

**Closed by 9876691** 2024-02-23 12:51 UTC
Labels: stalled
