### ISSUE TITLE
models request doesn't return expected output

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#128] opened 2023-11-30 12:00 UTC
curl -H "Authorization: Bearer $BIONIC_API_KEY" http://localhost:7800/v1/models

returns
{"data":[{"id":"h","object":"model","created":1677610602,"owned_by":"openai"},{"id":"u","object":"model","created":1677610602,"owned_by":"openai"},{"id":"g","object":"model","created":1677610602,"owned_by":"openai"},{"id":"g","object":"model","created":1677610602,"owned_by":"openai"},{"id":"i","object":"model","created":1677610602,"owned_by":"openai"},{"id":"n","object":"model","created":1677610602,"owned_by":"openai"},{"id":"g","object":"model","created":1677610602,"owned_by":"openai"},{"id":"f","object":"model","created":1677610602,"owned_by":"openai"},{"id":"a","object":"model","created":1677610602,"owned_by":"openai"},{"id":"c","object":"model","created":1677610602,"owned_by":"openai"},{"id":"e","object":"model","created":1677610602,"owned_by":"openai"},{"id":"/","object":"model","created":1677610602,"owned_by":"openai"},{"id":"I","object":"model","created":1677610602,"owned_by":"openai"},{"id":"n","object":"model","created":1677610602,"owned_by":"openai"},{"id":"t","object":"model","created":1677610602,"owned_by":"openai"},{"id":"e","object":"model","created":1677610602,"owned_by":"openai"},{"id":"l","object":"model","created":1677610602,"owned_by":"openai"},{"id":"/","object":"model","created":1677610602,"owned_by":"openai"},{"id":"n","object":"model","created":1677610602,"owned_by":"openai"},{"id":"e","object":"model","created":1677610602,"owned_by":"openai"},{"id":"u","object":"model","created":1677610602,"owned_by":"openai"},{"id":"r","object":"model","created":1677610602,"owned_by":"openai"},{"id":"a","object":"model","created":1677610602,"owned_by":"openai"},{"id":"l","object":"model","created":1677610602,"owned_by":"openai"},{"id":"-","object":"model","created":1677610602,"owned_by":"openai"},{"id":"c","object":"model","created":1677610602,"owned_by":"openai"},{"id":"h","object":"model","created":1677610602,"owned_by":"openai"},{"id":"a","object":"model","created":1677610602,"owned_by":"openai"},{"id":"t","object":"model","created":1677610602,"owned_by":"openai"},{"id":"-","object":"model","created":1677610602,"owned_by":"openai"},{"id":"7","object":"model","created":1677610602,"owned_by":"openai"},{"id":"b","object":"model","created":1677610602,"owned_by":"openai"},{"id":"-","object":"model","created":1677610602,"owned_by":"openai"},{"id":"v","object":"model","created":1677610602,"owned_by":"openai"},{"id":"3","object":"model","created":1677610602,"owned_by":"openai"},{"id":"-","object":"model","created":1677610602,"owned_by":"openai"},{"id":"1","object":"model","created":1677610602,"owned_by":"openai"}],"object":"list"}

Having looked more closely it looks like it is returning the model but not as multiple entries in list, one per letter

**Comment by ianpurton** [comment] 2023-12-01 08:18
For me this is working OK on the out of the box setup.

```
curl http://localhost:7800/v1/models \
  -H "content-type: application/json" \
  -H "authorization: Bearer $BIONIC_API_KEY"
  
 {"models":["llama-2"]}
```

Looks like you connecting to some model on huggingface? if so what happens when you call curl directly to that model?

Or how do I reproduce this?

**Comment by ianpurton** [comment] 2023-12-04 10:16
Closing as user non-responsive.

**Closed by ianpurton** 2023-12-04 10:16 UTC
