### ISSUE TITLE
Error occurred while generating.

### ISSUE THREAD

**Issue by brunoAmado** [bionic-gpt/bionic-gpt#351] opened 2024-01-29 13:19 UTC
### Describe your issue

trying bionic-gpt to a multilingual RAG. I embed documentation using "intfloat/multilingual-e5-large" and directly with the "Unbabel/TowerInstruct-7B-v0.1" model but trying the chat I always have "Error occurred while generating". Even changing Trim Ratio

### Describe your setup/startup scripts

```
   llmTowerInstruct-7B-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command:
      - /bin/sh
      - -c
      - |
        pip install async_generator
        litellm --model huggingface/Unbabel/TowerInstruct-7B-v0.1 --api_base http://${LOCALHOST_IP}:8102/generate_stream --host 0.0.0.0 --port 3307
    entrypoint: [ ]
    platform: linux/amd64
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "3307:3307"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    tgi-me5l-gpu-api:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    platform: linux/amd64
    command: --model-id intfloat/multilingual-e5-large
    volumes:
      - ./models:/data
    ports:
      - 8011:8011
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tgi-towerinstruct-gpu:
    image: ghcr.io/huggingface/text-generation-inference:latest
    command: --model-id Unbabel/TowerInstruct-7B-v0.1 --quantize eetq --num-shard 1 --max-batch-prefill-tokens 256 --max-input-length 256
    volumes:
      - ./models:/data
    ports:
      - 8102:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
```

### Steps to reproduce

![Captura de ecrã 2024-01-29 131448](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/c8be5fd5-3164-41d7-a545-054452bbe036)

**Comment by ianpurton** [comment] 2024-01-29 15:12
Do you have anything in the logs or in the browser console?

**Comment by brunoAmado** [comment] 2024-01-29 15:50
status = 422 Unprocessable Entity, message = query returned an unexpected number of rows

**Comment by brunoAmado** [comment] 2024-02-04 15:12
Hi @ianpurton it seams that 2 other person have created a related issue. But if you need something else to check please tell me.

**Comment by ianpurton** [comment] 2024-02-05 07:24
There are a few things going on here, you've changed the LLM and the embeddings.

I would go back to a config that works, then change one at a time, starting with just the model. 

That might help me see what the issue is.

**Comment by 9876691** [comment] 2024-02-09 12:34
May have been fixed in latest version, re-open otherwise.

**Closed by 9876691** 2024-02-09 12:34 UTC

**Comment by brunoAmado** [comment] 2024-02-10 17:07
I have some dns error even when I removing EMBEDDINGS_API_ENDPOINT (it seams that it use a "default" embedding endpoint but it is not the one I configure for the RAG. see error bellow:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/17bc369c-86f4-474b-9374-e534d67b1ccf)
removing the need for a DNS when putting a ip another error appear:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/d25a730f-f222-4330-8ee6-a9691fdc97ed)
